name: deep_simulator
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12
  - prophet=1.1.4
  - pandas==1.5.3
  - nltk==3.7
  - networkx==3.0
  - numpy==1.24.2
  - scikit-learn==1.2.2
  - hyperopt==0.2.5
  - jellyfish==0.9.0
  - tensorflow==2.11.1
  - keras==2.11.0
  - gensim==4.3.1
  - seaborn
  - backports.zoneinfo[tzdata]
  - pyyaml==6.0
  - click==8.1.7
  - pip:
    - fitter==1.5.2
    - pm4py==2.6.1
    - opyenxes==0.3.0
    - git+http://github.com/Mcamargo85/support_modules.git
